ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dohp.c mesh.c reduce.c
SOURCEF  =
SOURCEH  =
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libdohp
MANSEC   = DOHP
DIRS     =
LOCDIR   = src/interface/

include ${DOHP_DIR}/conf/base
