ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dohp.c mesh.c
SOURCEF  =
SOURCEH  =
OBJSC    = dohp.o
OBJSF    =
LIBBASE  = libdohp
MANSEC   = DOHP
DIRS     =
LOCDIR   = src/interface/

include ${DOHP_DIR}/conf/base
