/*****************************************************************************
*
* Copyright (c) 2000 - 2009, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400124
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtDohpFileFormat.C                           //
// ************************************************************************* //

#include <avtDohpFileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkUnstructuredGrid.h>
#include <vtkCellType.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>
#include <DebugStream.h>

#include <InvalidVariableException.h>
#include <InvalidZoneTypeException.h>
#include <InvalidDBTypeException.h>
#include <InvalidFilesException.h>

#include <vector>
#include <dohpvec.h>
#include <dohpsys.h>

// This exception is a copout, but VisIt doesn't offer many choices
#define avtCHK(err) do {						\
    if (err) {								\
      char buf[256];							\
      snprintf(buf,sizeof buf,"Error %d at %s:%d in %s()",(err),__FILE__,__LINE__,__PRETTY_FUNCTION__); \
      EXCEPTION1(ImproperUseException,buf);				\
    }									\
  } while (0)

// ****************************************************************************
//  Method: avtDohpFileFormat constructor
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

avtDohpFileFormat::avtDohpFileFormat(const char *filename)
  : avtMTMDFileFormat(filename)
{
  dErr err;
  dMPIInt flg;

  // The metadata server is "serial" which means it never uses MPI.  We are
  // always "parallel" in the sense that we use MPI even though we only ever use
  // MPI_COMM_SELF.
  err = MPI_Initialized(&flg);avtCHK(err);
  if (!flg) {
    err = MPI_Init(0,0);avtCHK(err);
  }
  PETSC_COMM_WORLD = MPI_COMM_SELF;
  err = dInitialize(0,0,0,0);avtCHK(err);
  {
    const char *debug = getenv("DOHP_DHM_DEBUG");
    if (debug) {
      if (!strcmp(debug,"on_error")) {err = PetscPushErrorHandler(PetscAttachDebuggerErrorHandler,NULL);avtCHK(err);}
      else if (!strcmp(debug,"start")) {err = PetscAttachDebugger();avtCHK(err);}
      else if (debug) {
        char buf[512];
        snprintf(buf,sizeof buf,"Unknown debugging flag set: '%s'",debug);
        EXCEPTION1(ImproperUseException,buf);
      }
    }
  }
  err = PetscViewerCreate(MPI_COMM_SELF,&this->viewer);avtCHK(err);
  err = PetscViewerSetType(this->viewer,PETSCVIEWERDHM);avtCHK(err);
  err = PetscViewerFileSetName(this->viewer,filename);avtCHK(err);
  err = PetscViewerFileSetMode(this->viewer,FILE_MODE_READ);avtCHK(err);
}

avtDohpFileFormat::~avtDohpFileFormat()
{
  /* Throwing exceptions in the destructor might cause a real problem. */
  PetscViewerDestroy(this->viewer);
  // I *think* it is fine to finalize Dohp+PETSc.  It is definitely not okay to
  // finalize MPI and then initialize it again, but this should not happen since
  // we called MPI_Init ourselves and nobody should be calling MPI_Finalize.
  dFinalize();
}

// ****************************************************************************
//  Method: avtEMSTDFileFormat::GetNTimesteps
//
//  Purpose:
//      Tells the rest of the code how many timesteps there are in this file.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

int
avtDohpFileFormat::GetNTimesteps(void)
{
  int ret;
  dInt nsteps;
  dReal *times;
  dErr err;

  err = dViewerDHMGetSteps(viewer,&nsteps,&times);avtCHK(err);
  ret = nsteps;
  err = dViewerDHMRestoreSteps(viewer,&nsteps,&times);avtCHK(err);
  return ret;
}


// ****************************************************************************
//  Method: avtDohpFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

void
avtDohpFileFormat::FreeUpResources(void)
{
  // We don't keep any internal state now
}


// ****************************************************************************
//  Method: avtDohpFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

void
avtDohpFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md, int timeState)
{
  const struct dViewerDHMSummaryFS *fspaces;
  const struct dViewerDHMSummaryField *fields;
  dInt nfspaces,nfields;
  dErr err;

  err = dViewerDHMSetTimeStep(this->viewer,timeState);avtCHK(err);
  err = dViewerDHMGetStepSummary(this->viewer,&nfspaces,&fspaces,&nfields,&fields);avtCHK(err);
  for (dInt i=0; i<nfspaces; i++) {
    int block_origin = 0,spatial_dimension = 3,topological_dimension = 3;
    double extents[6];
    for (int j=0; j<6; j++) extents[j] = ((dReal*)fspaces[i].boundingbox)[j];
    AddMeshToMetaData(md,fspaces[i].name,AVT_UNSTRUCTURED_MESH,extents,fspaces[i].nblocks,block_origin,spatial_dimension,topological_dimension);
  }
  for (dInt i=0; i<nfields; i++) {
    if (fields[i].bs == 1) {
      AddScalarVarToMetaData(md,fields[i].name,fields[i].fsname,AVT_NODECENT);
    } else {
      AddVectorVarToMetaData(md,fields[i].name,fields[i].fsname,AVT_NODECENT,fields[i].bs);
    }
  }
  err = dViewerDHMRestoreStepSummary(this->viewer,&nfspaces,&fspaces,&nfields,&fields);avtCHK(err);

  //
  // CODE TO ADD A MATERIAL
  //
  // string mesh_for_mat = meshname; // ??? -- could be multiple meshes
  // string matname = ...
  // int nmats = ...;
  // vector<string> mnames;
  // for (int i = 0 ; i < nmats ; i++)
  // {
  //     char str[32];
  //     sprintf(str, "mat%d", i);
  //     -- or -- 
  //     strcpy(str, "Aluminum");
  //     mnames.push_back(str);
  // }
  // 
  // Here's the call that tells the meta-data object that we have a mat:
  //
  // AddMaterialToMetaData(md, matname, mesh_for_mat, nmats, mnames);
  //
  //
  // Here's the way to add expressions:
  //Expression momentum_expr;
  //momentum_expr.SetName("momentum");
  //momentum_expr.SetDefinition("{u, v}");
  //momentum_expr.SetType(Expression::VectorMeshVar);
  //md->AddExpression(&momentum_expr);
  //Expression KineticEnergy_expr;
  //KineticEnergy_expr.SetName("KineticEnergy");
  //KineticEnergy_expr.SetDefinition("0.5*(momentum*momentum)/(rho*rho)");
  //KineticEnergy_expr.SetType(Expression::ScalarMeshVar);
  //md->AddExpression(&KineticEnergy_expr);
  //
}


// ****************************************************************************
//  Method: avtDohpFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      timestate   The index of the timestate.  If GetNTimesteps returned
//                  'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain      The index of the domain.  If there are NDomains, this
//                  value is guaranteed to be between 0 and NDomains-1,
//                  regardless of block origin.
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

vtkDataSet *
avtDohpFileFormat::GetMesh(int timestate, int domain, const char *meshname)
{
  vtkUnstructuredGrid *grid = vtkUnstructuredGrid::New();
  dFS fs;
  dInt nelem,nverts,nconn,*off,*conn;
  dEntTopology *topo;
  dErr err;

  err = dViewerDHMSetTimeStep(this->viewer,timestate);avtCHK(err);
  err = dFSCreate(MPI_COMM_SELF,&fs);avtCHK(err);
  err = dFSSetType(fs,dFSCONT);avtCHK(err);
  err = dFSSetOrderingType(fs,MATORDERINGNATURAL);avtCHK(err);
  err = dFSLoadIntoFS(this->viewer,meshname,fs);avtCHK(err);
  err = dFSGetSubElementMeshSize(fs,&nelem,&nverts,&nconn);avtCHK(err);
  off = new dInt[nelem+1];
  topo = new dEntTopology[nelem];
  conn = new dInt[nconn];
  err = dFSGetSubElementMesh(fs,nelem,nconn,topo,off,conn);avtCHK(err);

  for (dInt e=0; e<nelem; e++) {
    int econn[8];
    if (topo[e] != dTOPO_HEX) EXCEPTION1(InvalidZoneTypeException,topo[e]);
    if (off[e+1] - off[e] != 8) EXCEPTION1(InvalidZoneTypeException,topo[e]);
    for (dInt i=0; i<off[e+1]-off[e]; i++) {
      // Some day: check that value actually fits, only necessary if a single block has more than 2B elements
      econn[i] = conn[off[e]+i];
    }
    grid->InsertNextCell(VTK_HEXAHEDRON,8,econn);
  }

  {
    dInt n,bs;
    const dScalar *x;
    Vec X,Xc;
    err = dFSGetNodalCoordinatesGlobal(fs,&X);avtCHK(err);
    err = VecDohpGetClosure(X,&Xc);avtCHK(err);
    err = VecGetLocalSize(Xc,&n);avtCHK(err);
    err = VecGetBlockSize(Xc,&bs);avtCHK(err);
    if (bs != 3) EXCEPTION1(InvalidVariableException,"Unexpected block size bs != 3");
    if (n != nverts*bs) {       // This test will fail in parallel, need to map to a local vector
      char buf[512];
      snprintf(buf,sizeof buf,"Closure Vec of size %d with bs %d and FS with nverts=%d and nconn=%d do not agree about sizes",n,bs,nverts,nconn);
      PetscAttachDebugger();
      EXCEPTION1(InvalidVariableException,buf);
    }
    err = VecGetArrayRead(Xc,&x);avtCHK(err);
    vtkPoints *points = vtkPoints::New();
    points->SetNumberOfPoints(nverts);
    float *pts = (float*)points->GetVoidPointer(0);
    for (dInt i=0; i<n; i++) pts[i] = (float)x[i];
    grid->SetPoints(points);
    points->Delete();
    err = VecRestoreArrayRead(Xc,&x);avtCHK(err);
    err = VecDohpGetClosure(X,&Xc);avtCHK(err);
  }

  err = dFSDestroy(fs);avtCHK(err);
  delete [] off;
  delete [] topo;
  delete [] conn;
  return grid;
}


// ****************************************************************************
//  Method: avtDohpFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

vtkDataArray *
avtDohpFileFormat::GetVar(int timestate, int domain, const char *varname)
{
  dErr    err;
  dFS     fs;
  Vec     X,Xc;
  dScalar *x;
  dInt    n,bs;

  err = dViewerDHMSetTimeStep(this->viewer,timestate);avtCHK(err);
  err = dFSCreate(MPI_COMM_SELF,&fs);avtCHK(err);
  err = dFSSetType(fs,dFSCONT);avtCHK(err);
  err = dFSSetOrderingType(fs,MATORDERINGNATURAL);avtCHK(err);
  err = dFSLoadIntoFS(this->viewer,varname,fs);avtCHK(err);
  err = dFSCreateGlobalVector(fs,&X);avtCHK(err);
  err = VecDohpLoadIntoVector(this->viewer,varname,X);avtCHK(err);
  err = dFSDestroy(fs);avtCHK(err);

  err = VecDohpGetClosure(X,&Xc);avtCHK(err);
  err = VecGetLocalSize(Xc,&n);avtCHK(err);
  err = VecGetBlockSize(Xc,&bs);avtCHK(err);
  n /= bs;
  err = VecGetArray(Xc,&x);avtCHK(err);
  vtkFloatArray *var = vtkFloatArray::New();
  var->SetNumberOfComponents(bs);
  var->SetNumberOfTuples(n);
  for (int i=0; i<n; i++) {
    switch (bs) {
      case 1:
        var->SetTuple1(i,x[i]);
        break;
      case 3:
        var->SetTuple3(i,x[i*3+0],x[i*3+1],x[i*3+2]);
        break;
      default:
      {
        char buf[256];
        snprintf(buf,sizeof(buf),"Variable has size %d, don't know what to do with it",bs);
        EXCEPTION1(InvalidVariableException,buf);
      }
    }
  }
  err = VecRestoreArray(Xc,&x);avtCHK(err);
  err = VecDohpGetClosure(X,&Xc);avtCHK(err);
  err = VecDestroy(X);avtCHK(err);
  return var;
}


// ****************************************************************************
//  Method: avtDohpFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

vtkDataArray *
avtDohpFileFormat::GetVectorVar(int timestate, int domain,const char *varname)
{
  return this->GetVar(timestate,domain,varname);
}
