/*****************************************************************************
*
* Copyright (c) 2000 - 2009, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400124
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtDohpFileFormat.C                           //
// ************************************************************************* //

#include <avtDohpFileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>
#include <DebugStream.h>

#include <InvalidVariableException.h>
#include <InvalidDBTypeException.h>
#include <InvalidFilesException.h>

#include <vector>
#include <hdf5.h>

#define HCHK(herr,str) if ((herr) < 0) EXCEPTION1(InvalidFilesException,"Error in HDF5 function: " str "()")
#define HCALL(func,args) HCHK(func args,#func)

// ****************************************************************************
//  Method: avtDohpFileFormat constructor
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

avtDohpFileFormat::avtDohpFileFormat(const char *filename)
  : avtMTMDFileFormat(filename)
{
  hid_t  plist;
  plist = H5Pcreate(H5P_FILE_ACCESS);
#ifdef PARALLEL
  HCALL(H5Pset_fapl_mpio,(plist,VISIT_MPI_COMM,MPI_INFO_NULL));
#endif
  this->file = H5Fopen(filename,H5F_ACC_RDONLY,plist);
  if (this->file < 0) EXCEPTION1(InvalidFilesException,"Could not open file");
  HCALL(H5Pclose,(plist));
  this->grp_dohp = H5Gopen(this->file,"/dohp",H5P_DEFAULT);
  if (this->grp_dohp < 0) EXCEPTION1(InvalidDBTypeException,"File has no group \"/dohp\", cannot be a Dohp file");
}

avtDohpFileFormat::~avtDohpFileFormat()
{
  if (this->grp_dohp) HCALL(H5Gclose,(this->grp_dohp));
  if (this->file) HCALL(H5Fclose,(this->file));
}

// ****************************************************************************
//  Method: avtEMSTDFileFormat::GetNTimesteps
//
//  Purpose:
//      Tells the rest of the code how many timesteps there are in this file.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

int
avtDohpFileFormat::GetNTimesteps(void)
{
  return 100;
}


// ****************************************************************************
//  Method: avtDohpFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

void
avtDohpFileFormat::FreeUpResources(void)
{
}


// ****************************************************************************
//  Method: avtDohpFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

void
avtDohpFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md, int timeState)
{
  //
  // CODE TO ADD A MESH
  //
  string meshname = "FooMesh";
  //
  // AVT_RECTILINEAR_MESH, AVT_CURVILINEAR_MESH, AVT_UNSTRUCTURED_MESH,
  // AVT_POINT_MESH, AVT_SURFACE_MESH, AVT_UNKNOWN_MESH
  avtMeshType mt = AVT_RECTILINEAR_MESH;
  int nblocks = 1;
  int block_origin = 0;
  int spatial_dimension = 3;
  int topological_dimension = 3;
  double extents[6] = {-1,1,-1,1,-1,1};
  //
  // Here's the call that tells the meta-data object that we have a mesh:
  //
  AddMeshToMetaData(md, meshname, mt, extents, nblocks, block_origin,
                    spatial_dimension, topological_dimension);

  //
  // CODE TO ADD A SCALAR VARIABLE
  //
  string mesh_for_this_var = meshname;
  string varname = "BarVar";
  //
  // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
  avtCentering cent = AVT_NODECENT;
  //
  //
  // Here's the call that tells the meta-data object that we have a var:
  //
  AddScalarVarToMetaData(md, varname, mesh_for_this_var, cent);


  //
  // CODE TO ADD A VECTOR VARIABLE
  //
  // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
  // string varname = ...
  // int vector_dim = 2;
  //
  // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
  // avtCentering cent = AVT_NODECENT;
  //
  //
  // Here's the call that tells the meta-data object that we have a var:
  //
  // AddVectorVarToMetaData(md, varname, mesh_for_this_var, cent,vector_dim);
  //

  //
  // CODE TO ADD A TENSOR VARIABLE
  //
  // string mesh_for_this_var = meshname; // ??? -- could be multiple meshes
  // string varname = ...
  // int tensor_dim = 9;
  //
  // AVT_NODECENT, AVT_ZONECENT, AVT_UNKNOWN_CENT
  // avtCentering cent = AVT_NODECENT;
  //
  //
  // Here's the call that tells the meta-data object that we have a var:
  //
  // AddTensorVarToMetaData(md, varname, mesh_for_this_var, cent,tensor_dim);
  //

  //
  // CODE TO ADD A MATERIAL
  //
  // string mesh_for_mat = meshname; // ??? -- could be multiple meshes
  // string matname = ...
  // int nmats = ...;
  // vector<string> mnames;
  // for (int i = 0 ; i < nmats ; i++)
  // {
  //     char str[32];
  //     sprintf(str, "mat%d", i);
  //     -- or -- 
  //     strcpy(str, "Aluminum");
  //     mnames.push_back(str);
  // }
  // 
  // Here's the call that tells the meta-data object that we have a mat:
  //
  // AddMaterialToMetaData(md, matname, mesh_for_mat, nmats, mnames);
  //
  //
  // Here's the way to add expressions:
  //Expression momentum_expr;
  //momentum_expr.SetName("momentum");
  //momentum_expr.SetDefinition("{u, v}");
  //momentum_expr.SetType(Expression::VectorMeshVar);
  //md->AddExpression(&momentum_expr);
  //Expression KineticEnergy_expr;
  //KineticEnergy_expr.SetName("KineticEnergy");
  //KineticEnergy_expr.SetDefinition("0.5*(momentum*momentum)/(rho*rho)");
  //KineticEnergy_expr.SetType(Expression::ScalarMeshVar);
  //md->AddExpression(&KineticEnergy_expr);
  //
}


// ****************************************************************************
//  Method: avtDohpFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      timestate   The index of the timestate.  If GetNTimesteps returned
//                  'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain      The index of the domain.  If there are NDomains, this
//                  value is guaranteed to be between 0 and NDomains-1,
//                  regardless of block origin.
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

vtkDataSet *
avtDohpFileFormat::GetMesh(int timestate, int domain, const char *meshname)
{
  vtkRectilinearGrid *rect = vtkRectilinearGrid::New();
  int dims[3] = {101,101,101};
  vtkFloatArray *x = vtkFloatArray::New(),*y = vtkFloatArray::New(),*z = vtkFloatArray::New();

  x->SetNumberOfTuples(101);
  y->SetNumberOfTuples(101);
  z->SetNumberOfTuples(101);
  for (int i=0; i<101; i++) x->SetTuple1(i,-1.+2.*i/100);
  for (int i=0; i<101; i++) y->SetTuple1(i,-1.+2.*i/100);
  for (int i=0; i<101; i++) z->SetTuple1(i,-1.+2.*i/100);

  rect->SetDimensions(dims);
  rect->SetXCoordinates(x);
  rect->SetYCoordinates(y);
  rect->SetZCoordinates(z);
  x->Delete();
  y->Delete();
  z->Delete();
  return rect;
}


// ****************************************************************************
//  Method: avtDohpFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

vtkDataArray *
avtDohpFileFormat::GetVar(int timestate, int domain, const char *varname)
{
  vtkFloatArray *var = vtkFloatArray::New();
  var->SetNumberOfTuples(101*101*101);
  for (int i=0; i<101; i++) {
    for (int j=0; j<101; j++) {
      for (int k=0; k<101; k++) {
        double x = -1. + 2.*i/100;
        double y = -1. + 2.*j/100;
        double z = -1. + 2.*k/100;
        double t = 0.1*timestate;
        var->SetTuple1((i*101+j)*101+k,sin(0.2*t)*x*cos(y)*exp(z));
      }
    }
  }

  return var; //YOU_MUST_IMPLEMENT_THIS;

    //
    // If you have a file format where variables don't apply (for example a
    // strictly polygonal format like the STL (Stereo Lithography) format,
    // then uncomment the code below.
    //
    // EXCEPTION1(InvalidVariableException, varname);
    //

    //
    // If you do have a scalar variable, here is some code that may be helpful.
    //
    // int ntuples = XXX; // this is the number of entries in the variable.
    // vtkFloatArray *rv = vtkFloatArray::New();
    // rv->SetNumberOfTuples(ntuples);
    // for (int i = 0 ; i < ntuples ; i++)
    // {
    //      rv->SetTuple1(i, VAL);  // you must determine value for ith entry.
    // }
    //
    // return rv;
    //
    }


// ****************************************************************************
//  Method: avtDohpFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      timestate  The index of the timestate.  If GetNTimesteps returned
//                 'N' time steps, this is guaranteed to be between 0 and N-1.
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: jed -- generated by xml2avt
//  Creation:   Sat Oct 24 04:18:39 PDT 2009
//
// ****************************************************************************

vtkDataArray *
avtDohpFileFormat::GetVectorVar(int timestate, int domain,const char *varname)
{
  return 0; //YOU MUST IMPLEMENT THIS
    //
    // If you have a file format where variables don't apply (for example a
    // strictly polygonal format like the STL (Stereo Lithography) format,
    // then uncomment the code below.
    //
    // EXCEPTION1(InvalidVariableException, varname);
    //

    //
    // If you do have a vector variable, here is some code that may be helpful.
    //
    // int ncomps = YYY;  // This is the rank of the vector - typically 2 or 3.
    // int ntuples = XXX; // this is the number of entries in the variable.
    // vtkFloatArray *rv = vtkFloatArray::New();
    // int ucomps = (ncomps == 2 ? 3 : ncomps);
    // rv->SetNumberOfComponents(ucomps);
    // rv->SetNumberOfTuples(ntuples);
    // float *one_entry = new float[ucomps];
    // for (int i = 0 ; i < ntuples ; i++)
    // {
    //      int j;
    //      for (j = 0 ; j < ncomps ; j++)
    //           one_entry[j] = ...
    //      for (j = ncomps ; j < ucomps ; j++)
    //           one_entry[j] = 0.;
    //      rv->SetTuple(i, one_entry); 
    // }
    //
    // delete [] one_entry;
    // return rv;
    //
    }
