#
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#     DOHP - Dual order hp elements
#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#

CFLAGS   =
FFLAGS   =
SOURCEC  =
SOURCEF  =
SOURCEH  = dohp.h private/dohpimpl.h dohpmesh.h dohpbase.h
OBJSC    =
OBJSF    =
LIBBASE  = libdohp
DIRS     =
LOCDIR   = include/
MANSEC   = 

include ${DOHP_DIR}/conf/base
include ${DOHP_DIR}/conf/test

runexamples:

