#!/usr/bin/python

import tables as T
import optparse, warnings

def main():
    parser = optparse.OptionParser()
    parser.add_option("-o", "--output", dest="output", help="Output file")
    parser.add_option("-v", "--verbose", dest="verbose", action='store_true', default=False, help="Verbose warnings")
    opts, args = parser.parse_args()
    h5filename = args[0]
    if opts.verbose == False:
        warnings.filterwarnings('ignore', message="Type of attribute", category=UserWarning, module='tables', lineno=318)
        warnings.filterwarnings('ignore', message="leaf ", category=UserWarning, module='tables', lineno=378)
    hf = T.openFile(h5filename, 'r')
    for node in hf.walkNodes():
        print node

if __name__ == "__main__":
    main()
